pub(super) const SETUP_ONLY_LLM_CONTEXTS: &[&str] = &[
    "llm only during setup",
    "llm during setup only",
    "llm at setup time",
    "llm only during design",
    "llm only at design time",
    "llm only during compilation",
    "llm only at compile time",
    "llm only before deployment",
    "language model only during setup",
    "language model during setup only",
    "language model at setup time",
    "ai를 설정할 때만",
    "ai를 설정 시점에만",
    "llm을 설정할 때만",
    "llm을 설정 시점에만",
    "언어 모델을 설정할 때만",
    "언어 모델을 설정 시점에만",
];
pub(super) const SETUP_CONTEXT_BARRIERS: &[&str] = &[
    "generate initialization copy",
    "generate setup copy",
    "generate the setup copy",
    "llm during setup",
    "llm for setup",
    "language model during setup",
    "language model for setup",
    "llm before deployment",
    "llm while setting up",
    "language model before deployment",
    "language model while setting up",
];
pub(super) const SETUP_TIME_SUFFIXES: &[&str] = &[
    "at compile time",
    "at design time",
    "at initialization time",
    "at setup time",
    "before deployment",
    "during compilation",
    "during design",
    "during initialization",
    "during setup",
    "for setup",
    "in the setup phase",
    "once during initialization",
    "while setting up",
    "배포 전에",
    "설계 시점에",
    "설계할 때",
    "설정 단계",
    "설정 시점에",
    "설정할 때",
    "초기 설정 때",
    "컴파일 시점에",
    "컴파일할 때",
];
pub(super) const SETUP_ARTIFACT_PASSIVES: &[&str] =
    &["compiled", "created", "generated", "prepared"];
pub(super) const RESTART_MARKERS: &[&str] = &[
    "restart",
    "restarts",
    "reboot",
    "reboots",
    "재시작",
    "재부팅",
];
pub(super) const SURVIVAL_MARKERS: &[&str] = &[
    "persist",
    "persistent",
    "preserve",
    "keep",
    "retain",
    "restore",
    "survive",
    "without losing",
    "must not lose",
    "restart-safe",
    "restart safe",
    "영속",
    "유지",
    "보존",
    "복구",
    "살아",
    "잃지",
];
pub(super) const PERSISTENCE_SUBJECTS: &[&str] = &[
    "state",
    "data",
    "progress",
    "configuration",
    "records",
    "상태",
    "데이터",
    "진행",
    "설정",
    "기록",
];
pub(super) const PERSISTENCE_DIRECT: &[&str] = &[
    "restart_persistent",
    "restart-persistent",
    "restart persistent",
    "persist state",
    "재시작 후에도 상태를 유지",
    "재시작해도 상태를 유지",
    "재시작 후에도 데이터를 유지",
    "재시작해도 데이터를 유지",
    "재시작 후에도 진행 상태를 보존",
    "재시작해도 진행 상태를 보존",
    "재시작 후에도 잃지 않",
    "재시작해도 잃지 않",
];
pub(super) const PERSISTENT_STATE_MARKERS: &[&str] = &[
    "persistent state",
    "restart persistence",
    "state persistence",
    "영속 상태",
    "재시작 영속성",
];
pub(super) const POSITIVE_REQUIREMENT_ACTIONS: &[&str] = &[
    "add", "enable", "include", "need", "require", "store", "use", "using", "with", "추가", "포함",
    "사용", "유지", "저장", "필요",
];
pub(super) const POSITIVE_REQUIREMENT_SUFFIXES: &[&str] = &[
    "added", "enabled", "included", "required", "stored", "used", "추가", "포함", "사용", "저장",
    "진행", "유지", "필요",
];
pub(super) const POSITIVE_PERSISTENCE_ACTIONS: &[&str] = &[
    "keep",
    "keeps",
    "persist",
    "persists",
    "preserve",
    "preserves",
    "restore",
    "restores",
    "retain",
    "retains",
    "store",
    "stores",
    "survive",
    "survives",
    "복구",
    "보존",
    "살아",
    "영속",
    "유지",
    "저장",
];
pub(super) const PERSISTENCE_NEGATIONS: &[&str] = &[
    "do not persist state",
    "don't persist state",
    "do not persist data",
    "don't persist data",
    "do not preserve state",
    "don't preserve state",
    "do not preserve data",
    "don't preserve data",
    "do not retain state",
    "don't retain state",
    "do not restore state",
    "don't restore state",
    "state does not need to persist",
    "data does not need to persist",
    "state need not persist",
    "data need not persist",
    "do not use persistent state",
    "don't use persistent state",
    "without persistent state",
    "no persistent state",
    "without restart persistence",
    "no restart persistence",
    "persistent state is not required",
    "restart persistence is not required",
    "상태를 영속하지",
    "상태를 보존하지",
    "영속 상태를 사용하지",
    "영속 상태를 쓰지",
    "영속 상태 없이",
    "재시작 후 유지하지",
    "재시작해도 유지하지",
    "재시작 후에도 상태를 유지하지",
    "재시작해도 상태를 유지하지",
    "재시작 후에도 상태를 보존하지",
    "재시작해도 상태를 보존하지",
    "재시작 영속성 없이",
    "재시작 영속성은 필요 없",
];
pub(super) const NEGATED_PERSISTENCE_ACTIONS: &[&str] = &[
    "can't persist",
    "can't preserve",
    "can't retain",
    "can't restore",
    "can't survive",
    "cannot persist",
    "cannot preserve",
    "cannot retain",
    "cannot restore",
    "cannot survive",
    "can’t persist",
    "can’t preserve",
    "can’t retain",
    "can’t restore",
    "can’t survive",
    "can never persist",
    "can never preserve",
    "can never retain",
    "can never restore",
    "can never survive",
    "must never persist",
    "must never preserve",
    "must never retain",
    "must never restore",
    "must never survive",
    "must not persist",
    "must not preserve",
    "must not retain",
    "must not restore",
    "must not survive",
    "should not persist",
    "should not preserve",
    "should not retain",
    "should not restore",
    "should not survive",
    "shouldn't persist",
    "shouldn't preserve",
    "shouldn't retain",
    "shouldn't restore",
    "shouldn't survive",
    "shouldn’t persist",
    "shouldn’t preserve",
    "shouldn’t retain",
    "shouldn’t restore",
    "shouldn’t survive",
    "should never persist",
    "should never preserve",
    "should never retain",
    "should never restore",
    "should never survive",
    "does not need to persist",
    "does not need to survive",
    "does not persist",
    "does not preserve",
    "does not retain",
    "does not restore",
    "does not survive",
    "need not persist",
    "need not survive",
    "영속하지",
    "유지하지",
    "보존하지",
    "복구하지",
    "살아남지",
    "유지하면 안",
    "사용하지",
    "쓰지",
];

pub(super) const TIMER_MARKERS: &[&str] = &[
    "timer",
    "timers",
    "scheduler",
    "schedulers",
    "scheduled job",
    "타이머",
    "스케줄러",
    "예약 작업",
];
pub(super) const DURABLE_TIMER_PATTERNS: &[&str] = &[
    "durable timer",
    "durable timers",
    "persistent timer",
    "persistent timers",
    "durable scheduler",
    "durable schedulers",
    "persistent scheduler",
    "persistent schedulers",
    "restart-safe timer",
    "restart-safe timers",
    "restart safe timer",
    "restart safe timers",
    "timer must be durable",
    "timers must be durable",
    "timer must be persistent",
    "timers must be persistent",
    "scheduler must be durable",
    "schedulers must be durable",
    "scheduled job must be durable",
    "scheduled jobs must be durable",
    "timer survives restarts",
    "timers survive restarts",
    "timer must survive restarts",
    "timers must survive restarts",
    "quest timer must survive restarts",
    "quest timers must survive restarts",
    "영속 타이머",
    "내구성 타이머",
    "영속 스케줄러",
    "내구성 스케줄러",
    "재시작 후에도 유지되는 타이머",
    "재시작해도 유지되는 타이머",
    "타이머는 재시작 후에도 유지",
    "타이머가 재시작 후에도 유지",
    "타이머는 재시작해도 유지",
    "타이머가 재시작해도 유지",
];
pub(super) const DURABLE_TIMER_MARKERS: &[&str] = &[
    "durable scheduler",
    "durable schedulers",
    "durable timer",
    "durable timers",
    "persistent scheduler",
    "persistent schedulers",
    "persistent timer",
    "persistent timers",
    "restart safe timer",
    "restart safe timers",
    "restart-safe timer",
    "restart-safe timers",
    "내구성 스케줄러",
    "내구성 타이머",
    "영속 스케줄러",
    "영속 타이머",
];
pub(super) const DURABLE_TIMER_ASSERTIONS: &[&str] = &[
    "build durable timer",
    "build durable timers",
    "preserve durable timer",
    "preserve durable timers",
    "scheduled job must be durable",
    "scheduled jobs must be durable",
    "scheduler must be durable",
    "schedulers must be durable",
    "timer must be durable",
    "timer must be persistent",
    "timer must survive restarts",
    "timer survives restarts",
    "timers must be durable",
    "timers must be persistent",
    "timers must survive restarts",
    "timers survive restarts",
    "quest timer must survive restarts",
    "quest timers must survive restarts",
    "재시작 후에도 유지되는 타이머",
    "재시작해도 유지되는 타이머",
    "타이머가 재시작 후에도 유지",
    "타이머가 재시작해도 유지",
    "타이머는 재시작 후에도 유지",
    "타이머는 재시작해도 유지",
];
pub(super) const TIMER_NEGATIONS: &[&str] = &[
    "without durable timer",
    "without durable timers",
    "without persistent timer",
    "without persistent timers",
    "no durable timer",
    "no durable timers",
    "no persistent timer",
    "no persistent timers",
    "do not use durable timer",
    "do not use durable timers",
    "don't use durable timer",
    "don't use durable timers",
    "durable timers are not required",
    "timer durability is not required",
    "timers do not need to be durable",
    "timer does not need to be durable",
    "타이머 영속성 없이",
    "영속 타이머 없이",
    "내구성 타이머 없이",
    "영속 타이머를 사용하지",
    "영속 타이머를 안 사용",
    "영속 타이머를 안 써",
    "내구성 타이머를 사용하지",
    "영속 타이머 말고",
    "영속 타이머는 쓰지 마",
    "영속 타이머는 쓰지마",
    "영속 타이머는 안 써",
    "내구성 타이머는 쓰지 마",
    "내구성 타이머는 쓰지마",
    "타이머는 영속적일 필요 없",
];
pub(super) const NON_RUNTIME_TIMER_SURFACES: &[&str] = &[
    "timer button",
    "timer channel",
    "timer label",
    "timer message",
    "timer panel",
    "timer role",
];

pub(super) const ECONOMY_PERSISTENCE: &[&str] = &[
    "persistent xp",
    "persistent experience points",
    "persistent economy",
    "persistent balance",
    "xp storage",
    "experience points storage",
    "economy storage",
    "reward storage",
    "balance storage",
    "xp database",
    "economy database",
    "reward database",
    "balance database",
    "xp must be persistent",
    "xp must persist",
    "experience points must be persistent",
    "experience points must persist",
    "economy must be persistent",
    "economy must persist",
    "economy ledger must be persistent",
    "economy ledger must persist",
    "rewards must be persistent",
    "rewards must persist",
    "balances must be persistent",
    "balances must persist",
    "xp survives restarts",
    "keep xp across restarts",
    "preserve xp across restarts",
    "retain xp across restarts",
    "economy survives restarts",
    "reward balances survive restarts",
    "xp is stored persistently",
    "economy is stored persistently",
    "rewards are stored persistently",
    "balances are stored persistently",
    "영속 경험치",
    "영속 경제",
    "영속 보상",
    "영속 잔액",
    "경험치 저장소",
    "경제 저장소",
    "보상 저장소",
    "잔액 저장소",
    "경제 원장을 영속",
    "경제 원장은 영속",
    "경제 원장이 영속",
    "경험치를 영구 저장",
    "보상을 영구 저장",
    "잔액을 영구 저장",
];
pub(super) const ECONOMY_PERSISTENCE_MARKERS: &[&str] = &[
    "balance database",
    "balance storage",
    "economy database",
    "economy storage",
    "experience points storage",
    "persistent balance",
    "persistent economy",
    "persistent experience points",
    "persistent xp",
    "reward database",
    "reward storage",
    "xp database",
    "xp storage",
    "경제 저장소",
    "경험치 저장소",
    "보상 저장소",
    "영속 경제",
    "영속 경험치",
    "영속 보상",
    "영속 잔액",
    "잔액 저장소",
];
pub(super) const ECONOMY_PERSISTENCE_ASSERTIONS: &[&str] = &[
    "balances are stored persistently",
    "balances must be persistent",
    "balances must persist",
    "economy is stored persistently",
    "economy ledger must be persistent",
    "economy ledger must persist",
    "economy must be persistent",
    "economy must persist",
    "economy survives restarts",
    "experience points must be persistent",
    "experience points must persist",
    "keep xp across restarts",
    "preserve xp across restarts",
    "retain xp across restarts",
    "reward balances survive restarts",
    "rewards are stored persistently",
    "rewards must be persistent",
    "rewards must persist",
    "xp is stored persistently",
    "xp must be persistent",
    "xp must persist",
    "xp survives restarts",
    "경제 원장을 영속",
    "경제 원장은 영속",
    "경제 원장이 영속",
    "경험치를 영구 저장",
    "보상을 영구 저장",
    "잔액을 영구 저장",
];
pub(super) const ECONOMY_NEGATIONS: &[&str] = &[
    "without persistent xp",
    "without a persistent economy",
    "no persistent economy",
    "do not use a persistent economy",
    "do not use persistent economy",
    "don't use a persistent economy",
    "don't use persistent economy",
    "persistent economy is not required",
    "economy does not need to persist",
    "economy ledger does not need to be persistent",
    "영속 경제 없이",
    "영속 경제 말고",
    "영속 경제를 사용하지",
    "영속 경제를 안 사용",
    "영속 경제를 안 써",
    "경제 영속성 없이",
    "경제는 영속적일 필요 없",
];
pub(super) const ECONOMY_STORAGE_SUBJECTS: &[&str] = &[
    "xp",
    "experience points",
    "economy",
    "reward",
    "rewards",
    "balance",
    "balances",
    "ledger",
    "경험치",
    "경제",
    "보상",
    "잔액",
    "원장",
];
pub(super) const ECONOMY_STORAGE_NEGATING_ACTIONS: &[&str] = &[
    "do not persist",
    "do not store",
    "don't persist",
    "don't store",
    "don’t persist",
    "don’t store",
    "must not persist",
    "must not store",
    "never persist",
    "never store",
    "should not persist",
    "should not store",
    "without persisting",
    "without storing",
];

pub(super) const LLM_MARKERS: &[&str] = &[
    "llm",
    "language model",
    "artificial intelligence",
    "ai",
    "ai가",
    "ai는",
    "언어 모델",
    "인공지능",
];
pub(super) const NON_MODEL_LLM_SURFACES: &[&str] = &[
    " button", " channel", " label", " message", " modal", " panel", " role", " room", " 버튼",
    " 역할", " 채널", " 패널",
];
pub(super) const LLM_ACTIONS: &[&str] = &[
    "decide",
    "decides",
    "choose",
    "chooses",
    "generate",
    "generates",
    "evaluate",
    "evaluates",
    "infer",
    "infers",
    "invoked",
    "execute",
    "executes",
    "run",
    "runs",
    "결정",
    "선택",
    "생성",
    "평가",
    "추론",
    "실행",
    "호출",
];
pub(super) const LLM_PASSIVE_ACTIONS: &[&str] = &[
    "calling",
    "chosen by",
    "decided by",
    "evaluated by",
    "executed by",
    "generated by",
    "inferred by",
    "invoking",
    "run by",
];
pub(super) const EVENT_TIME_MARKERS: &[&str] = &[
    "at event time",
    "at runtime",
    "during an event",
    "during events",
    "when an event",
    "when the event",
    "on every message",
    "for every message",
    "per event",
    "이벤트 시점",
    "실행 시점",
    "요청 시점",
    "이벤트가 발생",
    "이벤트마다",
    "메시지마다",
];
pub(super) const EVENT_LLM_NEGATIONS: &[&str] = &[
    "without an llm",
    "without llm",
    "do not call an llm",
    "don't call an llm",
    "do not use an llm",
    "don't use an llm",
    "do not run an llm",
    "don't run an llm",
    "don’t call an llm",
    "don’t use an llm",
    "don’t run an llm",
    "must not call an llm",
    "never call an llm",
    "never let an llm",
    "never let the llm",
    "never ask an llm",
    "never ask the llm",
    "never run an llm",
    "never use an llm",
    "do not let an llm",
    "don't let an llm",
    "do not let the llm",
    "don't let the llm",
    "do not ask an llm",
    "don't ask an llm",
    "do not ask the llm",
    "don't ask the llm",
    "do not allow an llm",
    "do not allow the llm",
    "don't allow an llm",
    "don't allow the llm",
    "don’t allow an llm",
    "don’t allow the llm",
    "do not permit an llm",
    "do not permit the llm",
    "don't permit an llm",
    "don't permit the llm",
    "don’t permit an llm",
    "don’t permit the llm",
    "no event-time llm",
    "llm 없이",
    "언어 모델 없이",
    "인공지능 없이",
    "llm을 호출하지",
    "llm을 실행하지",
    "llm을 사용하지",
];
pub(super) const DIRECT_EVENT_LLM_NEGATIONS: &[&str] = &[
    "no event-time llm",
    "no event time llm",
    "이벤트 시점 llm 없이",
    "이벤트 시점 언어 모델 없이",
    "이벤트 시점 인공지능 없이",
];
pub(super) const NEGATED_LLM_ACTIONS: &[&str] = &[
    "must not decide",
    "must not choose",
    "must not generate",
    "must not evaluate",
    "must not infer",
    "must not execute",
    "must not run",
    "should not decide",
    "should not choose",
    "should not generate",
    "should not evaluate",
    "should not infer",
    "should not execute",
    "should not run",
    "does not decide",
    "does not choose",
    "does not generate",
    "does not evaluate",
    "does not infer",
    "does not execute",
    "does not run",
    "is forbidden to decide",
    "is forbidden to choose",
    "is forbidden to generate",
    "is forbidden to evaluate",
    "is forbidden to infer",
    "is forbidden to execute",
    "is forbidden to run",
    "are forbidden to decide",
    "are forbidden to choose",
    "are forbidden to generate",
    "are forbidden to evaluate",
    "are forbidden to infer",
    "are forbidden to execute",
    "are forbidden to run",
    "is not allowed to decide",
    "is not allowed to choose",
    "is not allowed to generate",
    "is not allowed to evaluate",
    "is not allowed to infer",
    "is not allowed to execute",
    "is not allowed to run",
    "are not allowed to decide",
    "are not allowed to choose",
    "are not allowed to generate",
    "are not allowed to evaluate",
    "are not allowed to infer",
    "are not allowed to execute",
    "are not allowed to run",
    "cannot decide",
    "cannot choose",
    "cannot generate",
    "cannot evaluate",
    "cannot infer",
    "cannot execute",
    "cannot run",
    "may not decide",
    "may not choose",
    "may not generate",
    "may not evaluate",
    "may not infer",
    "may not execute",
    "may not run",
    "never decide",
    "never choose",
    "never generate",
    "never evaluate",
    "never infer",
    "never execute",
    "never run",
    "결정하면 안",
    "결정해서는 안",
    "선택하면 안",
    "생성하면 안",
    "평가하면 안",
    "추론하면 안",
    "실행하면 안",
    "결정하지",
    "선택하지",
    "생성하지",
    "평가하지",
    "추론하지",
    "실행하지",
];
pub(super) const NEGATED_REQUIREMENT_USE_ACTIONS: &[&str] = &[
    "must not be added",
    "must not be included",
    "must not be stored",
    "must not be used",
    "must not be enabled",
    "must not be required",
    "must never be used",
    "must never be enabled",
    "must never be required",
    "should not be added",
    "should not be included",
    "should not be stored",
    "should not be used",
    "should not be enabled",
    "should not be required",
    "is not required",
    "are not required",
    "is forbidden",
    "are forbidden",
    "is not allowed",
    "are not allowed",
    "is prohibited",
    "are prohibited",
    "is disallowed",
    "are disallowed",
    "isn't required",
    "isn’t required",
    "aren't required",
    "aren’t required",
    "does not need to be used",
    "do not need to be used",
    "not needed",
    "unnecessary",
    "optional",
    "사용하지",
    "사용하면 안",
    "쓰지",
    "쓰면 안",
    "필요 없",
    "필요하지",
    "선택 사항",
    "금지",
];

pub(super) const NEGATING_ACTIONS: &[&str] = &[
    "avoid",
    "avoid using",
    "disable",
    "exclude",
    "omit",
    "remove",
    "do not add",
    "do not enable",
    "do not include",
    "do not let",
    "do not keep",
    "do not need",
    "do not persist",
    "do not preserve",
    "do not require",
    "do not restore",
    "do not retain",
    "do not use",
    "do not store",
    "without using",
    "cannot use",
    "can't use",
    "can’t use",
    "not use",
    "don't add",
    "don't enable",
    "don't include",
    "don't let",
    "don't keep",
    "don't need",
    "don't persist",
    "don't preserve",
    "don't require",
    "don't restore",
    "don't retain",
    "don't use",
    "don't store",
    "don’t add",
    "don’t enable",
    "don’t include",
    "don’t let",
    "don’t keep",
    "don’t need",
    "don’t persist",
    "don’t preserve",
    "don’t require",
    "don’t restore",
    "don’t retain",
    "don’t use",
    "don’t store",
    "use neither",
    "must not add",
    "must not enable",
    "must not include",
    "must not require",
    "must not use",
    "never add",
    "never enable",
    "never include",
    "never keep",
    "never persist",
    "never preserve",
    "never require",
    "never restore",
    "never retain",
    "never use",
    "no need for",
    "should not add",
    "should not enable",
    "should not include",
    "should not require",
    "should not use",
    "비활성화",
    "사용하지",
    "제거",
    "제외",
];

pub(super) const MAXIMUM_PROXIMITY_BYTES: usize = 1024;
