pub(super) const DATABASE_IDENTITY_FUNCTION: &str =
    "public.starring_product_lifecycle_cancellation_executor_database_identity_v1()";
pub(super) const KEYRING_COVERAGE_FUNCTION: &str =
    "public.starring_product_lifecycle_cancellation_keyring_coverage_v1(text[],text[])";
pub(super) const KEYRING_COVERAGE_ARGUMENTS: &str = "idempotency_digest_key_id_candidates text[], idempotency_digest_key_fingerprint_candidates text[]";
pub(super) const KEYRING_COVERAGE_RESULT: &str = "TABLE(outcome text)";
pub(super) const CANCEL_FUNCTION: &str = "public.starring_product_cancel_runtime_drain_v2(text,text,text,bigint,text,text,bytea,bytea,text,text,text,text,bigint,text,text,timestamp with time zone,timestamp with time zone,text,boolean,text,text,text[],text[],text[],text,text,text,text,text,text,text,text,bigint,text,text,bigint)";
pub(super) const CANCEL_ARGUMENTS: &str = "expected_tenant_id text, expected_installation_id text, expected_promotion_id text, expected_product_revision bigint, expected_payload_digest text, expected_principal_id text, expected_product_session_digest bytea, session_subject_digest bytea, expected_acting_user_id text, expected_discord_application_id text, expected_guild_id text, expected_capability text, expected_authority_revision bigint, expected_authority_payload_digest text, expected_authority_observation_digest text, expected_authority_observed_at timestamp with time zone, expected_authority_expires_at timestamp with time zone, expected_effective_permission_bits text, expected_guild_owner boolean, product_request_id text, active_idempotency_key_digest text, idempotency_key_digest_candidates text[], idempotency_digest_key_id_candidates text[], idempotency_digest_key_fingerprint_candidates text[], idempotency_digest_key_id text, semantic_request_digest text, new_receipt_id text, new_audit_event_id text, proposed_terminal_action_id text, expected_cancellation_reason text, expected_cancellation_reason_digest text, expected_drain_intent_id text, expected_source_intent_revision bigint, expected_source_state_digest text, expected_product_operation_id text, expected_source_deployment_revision bigint";
pub(super) const CANCEL_RESULT: &str = "TABLE(outcome_name text, exact_replay boolean, product_resulting_revision bigint, product_resulting_state text, guild_id text, product_receipt_id text, product_audit_event_id text, cancellation_reason_digest text, product_operation_id text, source_product_mutation_request_bytes bytea, product_mutation_digest text, source_drain_intent_request_bytes bytea, drain_intent_digest text, source_deployment_id text, source_deployment_revision bigint, source_deployment_snapshot jsonb, source_deployment_snapshot_digest text, source_result_deployment_revision bigint, source_result_deployment_snapshot jsonb, source_result_deployment_snapshot_digest text, drain_intent_id text, source_intent_revision bigint, source_state_bytes bytea, source_state_digest text, result_intent_revision bigint, result_intent_state text, result_state_bytes bytea, result_state_digest text, source_slot_epoch bigint, successor_slot_epoch bigint, terminal_action_id text, terminal_projection_bytes bytea, terminal_projection_digest text, terminal_database_time timestamp with time zone)";
pub(super) const TOPOLOGY_QUERY: &str = "SELECT \
     public.starring_product_lifecycle_cancellation_executor_database_identity_v1(), \
     current_database()::TEXT, current_user::TEXT, session_user::TEXT";
