pub(super) const DATABASE_IDENTITY_FUNCTION: &str =
    "public.starring_product_decision_reader_database_identity_v1()";
pub(super) const READ_FUNCTION: &str =
    "public.starring_product_decision_read_v1(text,text,text,text,text,text,bytea)";
pub(super) const READ_RESULT: &str = "TABLE(activation_request_id text, activation_tenant_id text, activation_installation_id text, activation_guild_id text, activation_ruleset_key text, activation_requester_id text, activation_required_approvals integer, activation_state text, activation_created_at timestamp with time zone, activation_expires_at timestamp with time zone, activation_promotion_request_digest text, activation_approval_payload_digest text, activation_approval_context jsonb, activation_product_revision bigint, approval_count bigint, promotion_tenant_id text, promotion_stage text, promotion_request_digest text, promotion_record jsonb, tenant_lifecycle_state text, installation_application_id text, installation_guild_id text, installation_ruleset_key text, installation_lifecycle_state text, installation_current_authority_revision bigint, current_authority_payload_digest text, promoted_session_owner_principal_id text, promoted_session_owner_discord_user_id text, promoted_generation_session_id text, promoted_generation bigint, promoted_generation_stage text, promoted_generation_candidate_revision bigint, promoted_generation_candidate_hash text, promoted_generation_resource_bindings jsonb, promoted_generation_binding_fingerprint text, historical_authority_binding_revision bigint, historical_authority_resource_bindings jsonb, historical_authority_resource_context_fingerprint text, historical_authority_policy_revision bigint, historical_authority_required_approvals integer, historical_authority_activation_ttl_seconds bigint, actor_discord_user_id text, actor_disabled boolean, actor_session_revoked_at timestamp with time zone, actor_session_idle_expires_at timestamp with time zone, actor_session_absolute_expires_at timestamp with time zone, runtime_deployment_id text, runtime_desired_target_digest text, database_now timestamp with time zone)";
pub(super) const READ_QUERY: &str =
    "SELECT * FROM public.starring_product_decision_read_v1($1, $2, $3, $4, $5, $6, $7) LIMIT 2";
pub(super) const TOPOLOGY_QUERY: &str = "SELECT \
     public.starring_product_decision_reader_database_identity_v1(), \
     current_database()::TEXT, current_user::TEXT, session_user::TEXT";
