[package]
name = "automation-ruleset-postgres"
version = "0.1.0"
edition.workspace = true

[dependencies]
automation-ruleset = { path = "../automation-ruleset" }
automation-state = { path = "../automation-state" }
discord-model = { path = "../discord-model" }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio-rustls", "postgres", "json", "derive", "macros", "migrate"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
