pub(in crate::turn) const ORDINARY_PREFIX_NEGATIONS: &[&str] = &[
    "do not",
    "don't",
    "dont",
    "don’t",
    "does not",
    "doesn't",
    "doesnt",
    "doesn’t",
    "did not",
    "didn't",
    "didnt",
    "didn’t",
    "isn't",
    "isnt",
    "isn’t",
    "aren't",
    "arent",
    "aren’t",
    "wasn't",
    "wasnt",
    "wasn’t",
    "weren't",
    "werent",
    "weren’t",
    "won't",
    "wont",
    "won’t",
    "wouldn't",
    "wouldnt",
    "wouldn’t",
    "couldn't",
    "couldnt",
    "couldn’t",
    "never",
    "neither",
    "must not",
    "mustn't",
    "mustn’t",
    "should not",
    "shouldn't",
    "shouldn’t",
    "cannot",
    "can't",
    "cant",
    "can’t",
    "not",
    "without",
    "no",
    "안",
    "못",
    "절대",
    "금지",
];

pub(in crate::turn) const PRESERVATION_PREFIX_NEGATIONS: &[&str] = &[
    "avoid",
    "prevent",
    "preventing",
    "disallow",
    "disallowing",
    "forbid",
    "forbidding",
    "refuse to",
    "stop",
];

pub(in crate::turn) const ACTION_NEGATION_MODIFIERS: &[&str] =
    &["also", "either", "ever", "immediately", "just", "only"];

pub(in crate::turn) const ACTION_POLARITY_TOKEN_WINDOW: usize = 16;

pub(in crate::turn) const SAFETY_CONTROL_TARGET_MODIFIERS: &[&str] =
    &["all", "any", "each", "every", "just", "only"];

pub(in crate::turn) const PRESERVATION_ACTOR_TERMS: &[&str] = &[
    "admin",
    "admins",
    "anyone",
    "automation",
    "bot",
    "bots",
    "everyone",
    "guest",
    "guests",
    "member",
    "members",
    "people",
    "someone",
    "system",
    "user",
    "users",
    "workflow",
];

pub(in crate::turn) const PRESERVATION_DETERMINERS: &[&str] =
    &["a", "all", "an", "any", "each", "every", "the"];

pub(in crate::turn) const CLOSED_SAFETY_CONTROL_TARGETS: &[&str] = &[
    "the design safety gates",
    "the human confirmation step",
    "the human approval",
    "the review gate",
    "the approval checkpoint",
    "the validation/preview stage",
    "the user approval",
    "the approval gate",
    "the approvals",
    "the approval",
    "the safety gates",
    "the safety gate",
    "the safety checks",
    "the safety check",
    "the safeguards",
    "the safeguard",
    "the validation",
    "the validator",
    "the preview",
    "design safety gates",
    "user approval",
    "user-approval",
    "human approval",
    "human confirmation step",
    "review gate",
    "consent",
    "approval checkpoint",
    "validation/preview stage",
    "approval gate",
    "approvals",
    "safety gates",
    "safety gate",
    "safety checks",
    "safety check",
    "safeguards",
    "safeguard",
    "validation",
    "validator",
    "preview",
    "approval",
];

pub(in crate::turn) const CLOSED_SAFETY_CONTROL_TARGET_TERMS: &[&str] = &[
    "approval",
    "check",
    "checkpoint",
    "checks",
    "gate",
    "gates",
    "preview",
    "confirmation",
    "consent",
    "human",
    "review",
    "stage",
    "safeguard",
    "safeguards",
    "safety",
    "user",
    "validation",
    "validator",
];

pub(in crate::turn) const CLOSED_SAFETY_CONTROL_SCOPE_PREPOSITIONS: &[&str] = &[
    "after", "before", "by", "during", "for", "from", "in", "on", "within",
];

pub(in crate::turn) const CLOSED_SAFETY_CONTROL_SCOPE_TERMS: &[&str] = &[
    "a",
    "actions",
    "admin",
    "admins",
    "all",
    "an",
    "any",
    "automation",
    "bot",
    "bots",
    "creation",
    "current",
    "design",
    "disabled",
    "each",
    "every",
    "feature",
    "flow",
    "game",
    "guest",
    "guests",
    "is",
    "member",
    "members",
    "anyone",
    "everyone",
    "people",
    "someone",
    "preview",
    "requested",
    "room",
    "rule",
    "system",
    "that",
    "the",
    "this",
    "user",
    "users",
    "workflow",
];

pub(in crate::turn) const CLOSED_SAFETY_CONTROL_SCOPE_HEADS: &[&str] = &[
    "actions",
    "admin",
    "admins",
    "automation",
    "bot",
    "bots",
    "creation",
    "design",
    "feature",
    "flow",
    "game",
    "guest",
    "guests",
    "member",
    "members",
    "anyone",
    "everyone",
    "people",
    "someone",
    "preview",
    "room",
    "rule",
    "system",
    "user",
    "users",
    "workflow",
];
