pub(in super::super) const GATE_TARGETS: &[&str] = &[
    "user approval",
    "user-approval",
    "human approval",
    "human confirmation step",
    "review gate",
    "consent",
    "approval checkpoint",
    "validation/preview stage",
    "validation",
    "validator",
    "preview",
    "approval",
    "safety gate",
    "safety gates",
    "safety check",
    "safety checks",
    "safeguard",
    "safeguards",
    "검증",
    "미리보기",
    "승인",
    "안전 게이트",
    "안전게이트",
    "안전 장치",
    "안전장치",
    "보호 장치",
    "보호장치",
];
pub(in super::super) const GATE_ACTIONS: &[&str] = &[
    "bypass",
    "bypasses",
    "bypassing",
    "skip",
    "skips",
    "skipping",
    "omit",
    "omits",
    "omitting",
    "disable",
    "disables",
    "disabling",
    "turns off",
    "turning off",
    "turn off",
    "ignore",
    "ignores",
    "ignoring",
    "우회",
    "건너뛰",
    "건너뛴",
    "생략",
    "무시",
    "끄",
    "제거",
    "없이",
    "거치지",
];
pub(in super::super) const GATE_DESTRUCTIVE_ACTIONS: &[&str] = &[
    "drop",
    "drops",
    "dropping",
    "eliminate",
    "eliminates",
    "eliminating",
    "remove",
    "removes",
    "removing",
];
pub(in super::super) const GATE_REQUIREMENT_REVERSAL_ACTIONS: &[&str] = &[
    "enforce",
    "enforces",
    "enforcing",
    "require",
    "requires",
    "requiring",
];
pub(in super::super) const GATE_REQUIREMENT_REVERSAL_PREDICATES: &[&str] =
    &["is disabled", "is forbidden", "is prohibited"];
pub(in super::super) const GATE_RESULT_ACTIONS: &[&str] = &[
    "accept",
    "approve",
    "assume",
    "auto-approve",
    "default",
    "implicit",
    "mark",
    "no-op",
    "noop",
    "passed",
    "set",
    "successful",
    "treat",
];
pub(in super::super) const GATE_ACTION_PERMISSION_PREDICATES: &[&str] = &[
    "is allowed",
    "is enabled",
    "is not disabled",
    "is not forbidden",
    "is not prohibited",
    "is permitted",
];
pub(in super::super) const GATE_EXACT_ACTIONS: &[&str] = &[
    "make approval optional",
    "make user approval optional",
    "make the user approval optional",
    "approval is optional",
    "user approval is optional",
    "approval is not needed",
    "user approval is not needed",
    "approval is not required",
    "user approval is not required",
    "approval isn't required",
    "user approval isn't required",
    "approval isnt required",
    "user approval isnt required",
    "approval isn’t required",
    "user approval isn’t required",
    "do not require user approval",
    "do not require approval",
    "don't require user approval",
    "don't require approval",
    "dont require user approval",
    "dont require approval",
    "don’t require user approval",
    "don’t require approval",
    "require no user approval",
    "require no approval",
    "승인을 빼줘",
    "승인만 빼줘",
    "사용자 승인을 빼줘",
    "승인을 없애줘",
    "승인만 없애줘",
    "사용자 승인을 없애줘",
    "승인을 빼주세요",
    "승인만 빼주세요",
    "사용자 승인을 빼주세요",
    "승인을 없애주세요",
    "승인만 없애주세요",
    "사용자 승인을 없애주세요",
    "승인을 요구하지 마",
    "사용자 승인을 요구하지 마",
    "승인을 요구하지마",
    "사용자 승인을 요구하지마",
    "승인을 요구하지 마세요",
    "사용자 승인을 요구하지 마세요",
    "승인을 요구하지마세요",
    "사용자 승인을 요구하지마세요",
];
pub(in super::super) const GATE_EXACT_ACTION_TERMS: &[&str] = &[
    "allow",
    "allowed",
    "are",
    "be",
    "bypassed",
    "disabled",
    "disallowed",
    "do",
    "does",
    "doesn't",
    "doesnt",
    "doesn’t",
    "don't",
    "dont",
    "don’t",
    "enabled",
    "enforce",
    "enforcing",
    "forbidden",
    "is",
    "isn't",
    "isnt",
    "isn’t",
    "make",
    "may",
    "must",
    "needed",
    "no",
    "not",
    "nobody",
    "one",
    "optional",
    "permitted",
    "permit",
    "proceed",
    "prohibited",
    "require",
    "required",
    "requiring",
    "ignored",
    "omitted",
    "removed",
    "skipped",
    "off",
    "turn",
    "turned",
    "turning",
    "turns",
    "should",
    "will",
];
pub(in super::super) const GATE_EXACT_PREFIX_WRAPPERS: &[&str] = &[
    "please carry out ",
    "carry out ",
    "do this: ",
    "execute ",
    "execute: ",
    "i want you to ",
    "i need you to ",
    "could you ",
    "would you ",
    "right away ",
    "right now ",
    "can you ",
    "will you ",
    "immediately ",
    "please ",
    "only ",
    "just ",
    "now ",
];
pub(in super::super) const GATE_EXACT_SUFFIX_WRAPPERS: &[&str] = &[
    " right away",
    " right now",
    " immediately",
    " please",
    " only",
    " now",
];
pub(in super::super) const GATE_EXACT_WRAPPER_TERMS: &[&str] = &[
    "also",
    "away",
    "can",
    "could",
    "i",
    "immediately",
    "just",
    "need",
    "now",
    "only",
    "please",
    "right",
    "to",
    "want",
    "will",
    "would",
    "you",
];
pub(in super::super) const LIVE_ACTIONS: &[&str] = &[
    "deploy",
    "deploys",
    "deploying",
    "deployed",
    "apply",
    "applies",
    "applying",
    "applied",
    "execute",
    "executes",
    "executing",
    "executed",
    "run",
    "runs",
    "running",
    "connect",
    "connects",
    "connecting",
    "connected",
    "touch",
    "touches",
    "touching",
    "touched",
    "create",
    "creates",
    "creating",
    "created",
    "delete",
    "deletes",
    "deleting",
    "deleted",
    "modify",
    "modifies",
    "modifying",
    "modified",
    "change",
    "changes",
    "changing",
    "changed",
    "publish",
    "publishes",
    "publishing",
    "published",
    "post",
    "posts",
    "posting",
    "posted",
    "grant",
    "grants",
    "granting",
    "granted",
    "revoke",
    "revokes",
    "revoking",
    "revoked",
    "rename",
    "renames",
    "renaming",
    "renamed",
    "edit",
    "edits",
    "editing",
    "edited",
    "update",
    "updates",
    "updating",
    "updated",
    "ban",
    "bans",
    "banning",
    "banned",
    "kick",
    "kicks",
    "kicking",
    "kicked",
    "send",
    "sends",
    "sending",
    "sent",
    "pin",
    "pins",
    "pinning",
    "pinned",
    "move",
    "moves",
    "moving",
    "moved",
    "push",
    "pushes",
    "pushing",
    "pushed",
    "activate",
    "activates",
    "activating",
    "activated",
    "remove",
    "removes",
    "removed",
    "assign",
    "assigns",
    "assigned",
    "give",
    "gives",
    "given",
    "strip",
    "strips",
    "stripped",
    "mute",
    "mutes",
    "muted",
    "timeout",
    "timeouts",
    "timed out",
    "unban",
    "unbans",
    "unbanned",
    "lock",
    "locks",
    "locked",
    "archive",
    "archives",
    "archived",
    "set",
    "sets",
    "add",
    "adds",
    "added",
    "upload",
    "uploads",
    "uploaded",
    "invite",
    "invites",
    "invited",
    "purge",
    "purges",
    "purged",
    "clear",
    "clears",
    "cleared",
    "unpin",
    "unpins",
    "unpinned",
    "unpublish",
    "unpublishes",
    "unpublished",
    "synchronize",
    "synchronizes",
    "synchronized",
    "배포",
    "적용",
    "실행",
    "연결",
    "건드",
    "생성",
    "삭제",
    "수정",
    "변경",
    "게시",
    "올리",
    "올려",
    "추가",
    "지우",
    "지워",
    "바꾸",
    "바꿔",
    "반영",
    "돌리",
    "돌려",
];
pub(super) const LIVE_THIRD_PERSON_ACTIONS: &[&str] = &[
    "activates",
    "adds",
    "applies",
    "archives",
    "assigns",
    "bans",
    "changes",
    "clears",
    "connects",
    "creates",
    "deletes",
    "deploys",
    "edits",
    "executes",
    "gives",
    "grants",
    "invites",
    "kicks",
    "locks",
    "modifies",
    "moves",
    "mutes",
    "pins",
    "posts",
    "publishes",
    "purges",
    "pushes",
    "renames",
    "removes",
    "revokes",
    "runs",
    "sends",
    "sets",
    "strips",
    "synchronizes",
    "timeouts",
    "touches",
    "updates",
    "unbans",
    "unpins",
    "unpublishes",
    "uploads",
];
pub(super) const LIVE_BASE_ACTIONS: &[&str] = &[
    "activate",
    "add",
    "apply",
    "archive",
    "assign",
    "ban",
    "change",
    "clear",
    "connect",
    "create",
    "delete",
    "deploy",
    "edit",
    "execute",
    "give",
    "grant",
    "invite",
    "kick",
    "lock",
    "modify",
    "move",
    "mute",
    "pin",
    "post",
    "publish",
    "purge",
    "push",
    "remove",
    "rename",
    "revoke",
    "run",
    "send",
    "set",
    "strip",
    "synchronize",
    "timeout",
    "touch",
    "unban",
    "unpin",
    "unpublish",
    "update",
    "upload",
];
pub(super) const LIVE_PASSIVE_ACTIONS: &[&str] = &[
    "activated",
    "added",
    "applied",
    "archived",
    "assigned",
    "banned",
    "changed",
    "cleared",
    "connected",
    "created",
    "deleted",
    "deployed",
    "edited",
    "executed",
    "given",
    "granted",
    "invited",
    "kicked",
    "locked",
    "modified",
    "moved",
    "muted",
    "pinned",
    "posted",
    "published",
    "purged",
    "pushed",
    "renamed",
    "removed",
    "revoked",
    "run",
    "sent",
    "set",
    "stripped",
    "synchronized",
    "timed out",
    "touched",
    "updated",
    "unbanned",
    "unpinned",
    "unpublished",
    "uploaded",
];
pub(in super::super) const LIVE_CONTEXT: &[&str] = &[
    "live-discord",
    "live environment",
    "live guild",
    "live discord",
    "live server",
    "production discord",
    "production environment",
    "production guild",
    "production server",
    "actual discord",
    "actual server",
    "discord now",
    "실서버",
    "라이브 디스코드",
    "라이브 서버",
    "운영 디스코드",
    "운영 서버",
    "운영서버",
    "실제 디스코드",
    "실제 서버",
];
pub(in super::super) const LIVE_CONTEXT_ALIASES: &[&str] = &["prod", "production"];
pub(super) const LIVE_MUTABLE_RESOURCE_TARGETS: &[&str] = &[
    "category",
    "categories",
    "channel",
    "channels",
    "command",
    "commands",
    "emoji",
    "emojis",
    "guild",
    "guilds",
    "invite",
    "invites",
    "member",
    "members",
    "message",
    "messages",
    "panel",
    "panels",
    "permission",
    "permissions",
    "role",
    "roles",
    "server",
    "servers",
    "sticker",
    "stickers",
    "thread",
    "threads",
    "webhook",
    "webhooks",
];
pub(super) const LIVE_RESOURCE_DESCRIPTION_TARGETS: &[&str] = &[
    "analysis",
    "diagram",
    "documentation",
    "guide",
    "guidance",
    "metrics",
    "preview",
    "report",
    "snapshot",
    "status",
    "tutorial",
];
pub(in super::super) const IMMEDIATE_CONTEXT: &[&str] = &[
    "now",
    "immediately",
    "right away",
    "directly",
    "at once",
    "지금",
    "즉시",
    "바로",
    "직접",
    "당장",
    "실제로",
];
pub(in super::super) const SECRET_TARGETS: &[&str] = &[
    "secret",
    "secrets",
    "api key",
    "api keys",
    "api-key",
    "api-keys",
    "api_key",
    "api_keys",
    "api token",
    "api tokens",
    "api-token",
    "api-tokens",
    "api_token",
    "api_tokens",
    "bearer token",
    "bearer tokens",
    "connection string",
    "connection strings",
    "cookie",
    "cookies",
    "database connection string",
    "database connection strings",
    "dsn",
    "dsns",
    "encryption key",
    "encryption keys",
    "jwt",
    "jwts",
    "private key",
    "private keys",
    "session cookie",
    "session cookies",
    "session token",
    "session tokens",
    "signing key",
    "signing keys",
    "ssh key",
    "ssh keys",
    "access key",
    "access keys",
    "access token",
    "access tokens",
    "access-token",
    "access-tokens",
    "token",
    "tokens",
    "credential",
    "credentials",
    "password",
    "passwords",
    "environment variable",
    "environment variables",
    "env var",
    "env vars",
    "비밀",
    "api 키",
    "api키",
    "액세스 키",
    "토큰",
    "자격 증명",
    "자격증명",
    "비밀번호",
    "암호",
    "환경 변수",
    "환경변수",
    "키 값",
];
pub(in super::super) const SECRET_ACTIONS: &[&str] = &[
    "expose",
    "exposes",
    "exposing",
    "exposed",
    "reveal",
    "reveals",
    "revealing",
    "revealed",
    "disclose",
    "discloses",
    "disclosing",
    "disclosed",
    "publish",
    "publishes",
    "publishing",
    "published",
    "post",
    "posts",
    "posting",
    "posted",
    "show",
    "shows",
    "showing",
    "shown",
    "display",
    "displays",
    "displaying",
    "displayed",
    "print",
    "prints",
    "printing",
    "printed",
    "include",
    "includes",
    "including",
    "included",
    "contains",
    "contained",
    "appears",
    "present",
    "put",
    "puts",
    "send",
    "sends",
    "sending",
    "sent",
    "leak",
    "leaks",
    "leaking",
    "leaked",
    "go",
    "goes",
    "going",
    "went",
    "gone",
    "공개",
    "노출",
    "게시",
    "보여",
    "표시",
    "출력",
    "전송",
    "넣",
    "포함",
    "유출",
    "보내",
    "공유",
    "올리",
    "올라가",
    "적",
    "알리",
];
pub(super) const SECRET_THIRD_PERSON_ACTIONS: &[&str] = &[
    "appears",
    "contains",
    "discloses",
    "displays",
    "exposes",
    "goes",
    "includes",
    "leaks",
    "posts",
    "prints",
    "publishes",
    "puts",
    "reveals",
    "sends",
    "shows",
];
pub(super) const SECRET_BASE_ACTIONS: &[&str] = &[
    "disclose", "display", "expose", "go", "include", "leak", "post", "print", "publish", "put",
    "reveal", "send", "show",
];
pub(super) const SECRET_PASSIVE_ACTIONS: &[&str] = &[
    "contained",
    "disclosed",
    "displayed",
    "exposed",
    "gone",
    "included",
    "leaked",
    "posted",
    "printed",
    "published",
    "put",
    "present",
    "revealed",
    "sent",
    "shown",
];
pub(in super::super) const CLOSED_THIRD_PERSON_BOUNDARY_ACTORS: &[&str] = &[
    "agent",
    "agents",
    "alert",
    "alerts",
    "application",
    "applications",
    "automation",
    "automations",
    "bot",
    "bots",
    "detector",
    "detectors",
    "handler",
    "handlers",
    "job",
    "jobs",
    "process",
    "processes",
    "rule",
    "rules",
    "service",
    "services",
    "server",
    "servers",
    "system",
    "systems",
    "worker",
    "workers",
    "workflow",
    "workflows",
    "warning",
    "warnings",
];
pub(in super::super) const CLOSED_SECRET_DISCLOSURE_ACTORS: &[&str] = &[
    "embed",
    "embeds",
    "message",
    "messages",
    "panel",
    "panels",
    "post",
    "posts",
    "response",
    "responses",
];
pub(in super::super) const CLOSED_BOUNDARY_ACTION_ADVERBS: &[&str] = &[
    "also",
    "always",
    "automatically",
    "currently",
    "deliberately",
    "directly",
    "first",
    "firstly",
    "immediately",
    "just",
    "next",
    "now",
    "only",
    "publicly",
    "remotely",
    "then",
    "afterward",
    "afterwards",
    "up",
];
pub(in super::super) const SAFE_REDACTION: &[&str] = &[
    "redact",
    "redacted",
    "mask",
    "masked",
    "substitute",
    "substituted",
    "replace",
    "replaced",
    "가림",
    "가려",
    "마스킹",
    "대체",
    "치환",
    "숨김",
    "숨겨",
];
pub(in super::super) const UNPROTECTED_SECRET: &[&str] = &[
    "without redaction",
    "without masking",
    "unredacted",
    "unmasked",
    "do not redact",
    "don't redact",
    "dont redact",
    "never redact",
    "do not mask",
    "don't mask",
    "dont mask",
    "redaction disabled",
    "masking disabled",
    "mask=false",
    "mask = false",
    "가리지 말",
    "가림 없이",
    "마스킹 없이",
    "대체하지 말",
    "숨기지 말",
];
pub(in super::super) const SECRET_DELIVERY_CONTEXT: &[&str] = &[
    "public",
    "publicly",
    "everyone",
    "panel",
    "message",
    "response",
    "channel",
    "공개",
    "모두",
    "패널",
    "메시지",
    "응답",
    "채널",
];
pub(in super::super) const GATE_CONTROL_TERMS: &[&str] = &[
    "all",
    "any",
    "avoid",
    "disallow",
    "disallowing",
    "do",
    "don't",
    "dont",
    "don’t",
    "forbid",
    "forbidding",
    "from",
    "hesitate",
    "must",
    "mustn't",
    "mustn’t",
    "never",
    "no",
    "not",
    "prevent",
    "preventing",
    "refuse",
    "should",
    "shouldn't",
    "shouldn’t",
    "stop",
    "the",
    "without",
    "안",
    "절대",
    "금지",
    "못",
];
pub(in super::super) const SUFFIX_NEGATIONS: &[&str] = &[
    "not",
    "n't",
    "is forbidden",
    "is prohibited",
    "is disabled",
    "하지",
    "하지마",
    "하지마세요",
    "하지말고",
    "하지 마",
    "하지 말고",
    "하지 마세요",
    "하지 않",
    "하지 않고",
    "지 않",
    "지 않고",
    "지마",
    "지마세요",
    "지 마",
    "지 말고",
    "지 마세요",
    "지 말",
    "않아",
    "않고",
    "말아",
    "말고",
    "금지",
    "안 해",
    "안 함",
    "못 해",
    "를 막",
    "을 막",
    "를 금지",
    "을 금지",
    "되지 않게",
    "되지 못하게",
    "지 않게",
    "지 못하게",
];
