[package]
name = "automation-stateful-compiler"
version = "0.1.0"
edition.workspace = true

[dependencies]
automation-spec = { path = "../automation-spec" }
automation-state = { path = "../automation-state" }
automation-stateful-spec = { path = "../automation-stateful-spec" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10"
thiserror = { workspace = true }

[dev-dependencies]
automation-core = { path = "../automation-core" }
